# -*- coding: utf-8 -*-
"""Variables_and_Input_in_Python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19p82VgOHFL-BbysbDVksimn3fVhJ7LLY
"""

#_Variables_in_Python : is a name given to memory location in a program.

#_Variables = Values

first_name = "Suneel"
last_name = "Shivani"
age = 21

print(first_name)
print("My name is:", first_name)

#Or

name = first_name = "Suneel"
print(name)

#_input_in_python:

#_1.

name = input("what is you superhero name?")

print(name)

#_2.

age = input("What is your age?")

print("Hello " + age + " years old man.")

#_3

first = input("the frist number is ")
second = input("the second number is ")

sum = int(first) + int(second)

print(sum)

#_4.

old_age = input("what is your old age?")
new_age = int(old_age) + 5

print(new_age)

#_5.

email = input("Enter you email:")

print(email)

#_6.

name = inpput("enter your name:")
age = input("enter your age")
score = input("your score")

print("Welcome", name)
print("my age is", age)
print(score)

#_7.

age = int(input("enter you age:"))
age = 2024 - age

print(age)